### ISSUE TITLE
Plantage lorsqu'on ouvre la page Ludi sans être identifié

### ISSUE THREAD

**Issue by emmrichard** [axel584/samopiniuloj-por-android#79]
Lorsqu'on n'est pas identifié, si on ouvre la page Ludi en la sélectionnant dans le menu, l'application s'arrête

**Comment by emmrichard** [comment]
1. Je désinstalle l'appli, puis je la lance sur ma tablette depuis Android Studio
   --> La page "eniri" s'affiche
2. Dans le menu je sélectionne "Ludi"
   --> Le toast "konaktiĝas" s'affiche pour l'application se ferme automatiquement
   
   Process: org.esperanto_france.samopiniuloj, PID: 2387
   java.lang.RuntimeException: An error occured while executing doInBackground()
           at android.os.AsyncTask$3.done(AsyncTask.java:300)
           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
           at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
           at java.lang.Thread.run(Thread.java:841)
    Caused by: java.lang.NullPointerException
           at org.esperanto_france.samopiniuloj.LudiFragment$NovajVortojAsyncTask.doInBackground(LudiFragment.java:559)
           at org.esperanto_france.samopiniuloj.LudiFragment$NovajVortojAsyncTask.doInBackground(LudiFragment.java:528)
           at android.os.AsyncTask$2.call(AsyncTask.java:288)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
               at java.lang.Thread.run(Thread.java:841)
   05-19 22:39:51.376    2387-2387/org.esperanto_france.samopiniuloj E/WindowManager﹕ android.view.WindowLeaked: Activity org.esperanto_france.samopiniuloj.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{268b2690 V.E..... R......D 0,0-959,192} that was originally added here
           at android.view.ViewRootImpl.<init>(ViewRootImpl.java:370)
           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
           at android.app.Dialog.show(Dialog.java:286)
           at org.esperanto_france.samopiniuloj.LudiFragment$NovajVortojAsyncTask.onPreExecute(LudiFragment.java:543)
           at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
           at android.os.AsyncTask.execute(AsyncTask.java:535)
           at org.esperanto_france.samopiniuloj.LudiFragment.onCreateView(LudiFragment.java:170)
           at android.app.Fragment.performCreateView(Fragment.java:1700)
           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
           at android.app.BackStackRecord.run(BackStackRecord.java:685)
           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
           at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
           at android.os.Handler.handleCallback(Handler.java:733)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:149)
           at android.app.ActivityThread.main(ActivityThread.java:5257)
           at java.lang.reflect.Method.invokeNative(Native Method)
           at java.lang.reflect.Method.invoke(Method.java:515)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
           at dalvik.system.NativeStart.main(Native Method)

**Comment by emmrichard** [comment]
je n'arrive plus à reproduire le bug. Je pense que c'est corrigé.
