### ISSUE TITLE
Sur la pagho "eniri", musklikante sur la butono "aligxu" kolapsas la aplikajhon.

### ISSUE THREAD

**Issue by axel584** [axel584/samopiniuloj-por-android#84]

**Comment by emmrichard** [comment]
J'ai testé avec ma tablettes et plusieurs émulateurs différents : je ne reproduis le problème qu'avec la v21 ou la v22.

Le problème semble venir du Spinner utilisé pour la liste des pays. J'ai cette trace quand je lance un émulateur avec l'API 21 
    --------- beginning of crash
05-20 23:17:35.457    2269-2269/org.esperanto_france.samopiniuloj E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.esperanto_france.samopiniuloj, PID: 2269
    java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
            at android.widget.Spinner.setAdapter(Spinner.java:439)
            at org.esperanto_france.samopiniuloj.AlighiFragment.onCreateView(AlighiFragment.java:310)
            at android.app.Fragment.performCreateView(Fragment.java:2053)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:833)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by emmrichard** [comment]
http://stackoverflow.com/questions/28328592/spinner-error-spinner-adapter-view-type-count-must-be-1
https://code.google.com/p/android/issues/detail?id=79011
